import { Ubuntu } from "next/font/google";
import "@/styles/base.scss";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { ToastContainer } from "react-toastify";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <Header />
        <main className="site">{children}</main>
        <Footer />
        <ToastContainer />
      </body>
    </html>
  );
}
